### ISSUE TITLE
Operation support 

### ISSUE THREAD

**Issue by rdingwell** [Asymmetrik/node-fhir-server-core#102]
Hi,
I have a couple of quick questions. 
1. Is there a means to support FHIR operations?  It looks like there is all of the basic CRUD and searching type stuff but I do not see how one would go about implementing operations within the framework.  This would be for spec defined operations such as Patient $everything as well as custom site defined operations. 

2. Is there something along the lines of a google group for asking questions or interacting with other users of the framework?  Github issues are good for somethings, groups are better for others, IMO anyway. 

Thanks

**Comment by dominathan** [comment]
I am out of the country at the moment. But I also was planning on working on this feature. 

I was planning on adding it to the config object that would create routes based on the defined name. I'm open to other ideas. 

Nathan

**Comment by rdingwell** [comment]
@dominathan  
I think the config object is a fine place for that functionality to be declared.   Just a thought, but you could probably allow for a few different types of operation implementations too, mapped to methods on the service, require statements, or just passing a method directly.  Of course that could just be a really over engineered idea too. 

Rob

**Comment by dominathan** [comment]
@jonterrylee 

This is what I have in the config file.  It's an addition to a profile which is just an array of operations.

```js
profiles: {
		medication: {
			service: path.resolve('./src/medications/index'),
			versions: [VERSIONS['3_0_1']],
			operation: [
				{
					name: 'duplicateTherapy',
					route: 'duplicate-therapy',
					method: 'POST'
				},
				{
					name: 'drugDrugInteraction',
					route: 'drug-drug-interaction',
					method: 'POST'
				},
				{
					name: 'drugAllergyInteraction',
					route: 'drug-allergy-interaction',
					method: 'POST'
				}
			]
		},
```
I then have checks to make sure the service path has function names that are exported to match the `operation.name ` provided or it fails the build. 

How do you feel about this?  I have some more cleaning up and testing but I figured I check in before I keep going down this road.

**Comment by rdingwell** [comment]
I think this a decent approach but I have a few questions.  

What scopes are required to access a given operation? Is that something that needs to be planned now or can it be something that is worked out over time?  

Is there any sort of parameter sanitization that goes along with the operations?  I would think to begin with that there doesn't need to be any to keep things pretty open and flexible and add overtime is required. 

Does there need to be any kind of indication as to what type of operation it is, system, resource-type, resource-instance?   Does this effect scopes in anyway? 

Are GET and POST methods supported or only POST? 

Personally, I think leaving it pretty open and allowing the implementation of the operation to handle everything is the best way to start.  Additional constraints can be added as required.

**Comment by dominathan** [comment]
* Same scopes that we give to GET and POST for profile requests will be given to the operations.
* Right now the only parameters allowed and sanitized are the ones that are global fhir search parameters
*  I'm not sure I correctly understand your third question.  As of now, it will work on all /:resource_type that you place the operation under in the config file.  As of now, I'm not doing operations on resource instances but it shouldn't be too difficult to add in the future ...`if (args.id)` -> handleResourceInstance.
* GET and POST will be allowed

I should have  a pull request up to be looked at in the next few hours.

**Comment by rdingwell** [comment]
Thanks.  The third question pertains to the types of operations the FHIR spec lays out: 

system: the URL is [base]/$[name]
resource type: the URL is [base]/[type]/$[name]
resource instance: the URL is [base]/[type]/[id]/$[name]

My main use case to begin with would be to implement the Patient/[id]/$everything and Encounter/[id]/$everything operations, which are resource instance based.

**Comment by dominathan** [comment]
@rdingwell  @jonterrylee take a look at #111 for the pull request.

**Comment by Robert-W** [comment]
Thanks @dominathan, closing this since that PR was merged.
