### ISSUE TITLE
bump nodemon to remove malicious package

### ISSUE THREAD

**Issue by mcdemarco** [Asymmetrik/node-fhir-server-core#106]
### Do you want to request a feature, improve documentation, or ask a question?

No.

### Are you reporting a bug?

Yes.

**What is the current behavior?**

A critical issue on npm install: malicious package flatmap-stream.

**What is the expected behavior?**

No critical issues.

**What are the steps to reproduce?**

npm install (against the current package.json on master).

**What OS are you using and what version of node.js and @asymmetrik/fhir-server-core are you running?**

MacOS, node 10.5.0, dev branch of the project.

An adequate fix, bumping nodemon to 1.18.6, is documented here:  https://github.com/reactioncommerce/reaction/pull/4828

The current version is 1.12.1.

**Comment by jonterrylee** [comment]
thanks @mcdemarco 

I've made a pr to fix this issue.  
[#107](https://github.com/Asymmetrik/node-fhir-server-core/pull/107)

**Comment by Robert-W** [comment]
Merged, thanks guys
