### ISSUE TITLE
Document authentication changes

### ISSUE THREAD

**Issue by mcdemarco** [Asymmetrik/node-fhir-server-core#108]
### Do you want to request a feature, improve documentation, or ask a question?

Improve documentation.

**What is the current behavior?**

Authentication has changed to use PassportJS and is no longer documented.  Nor is it clear from the existing documentation that it no longer applies.

A particular issue with the change in setup is that there is no Passport strategy example given, and authentication does not turn on without one.  (There was some discussion of this at the end of issue #58.)

An example would also be helpful, as PassportJS is cryptic about authentication failures.

**Comment by Robert-W** [comment]
Going to link this in another issue. I have decided to create one issue to track all necessary documentation changes and additions. Closing this since it will be linked in the other issue.
