### ISSUE TITLE
'part' attribute missing from Parameters object

### ISSUE THREAD

**Issue by jtravan3** [Asymmetrik/node-fhir-server-core#113]
The 'part' attribute is missing from the v3.0.1 Parameters object (see reference here: http://www.hl7.org/fhir/parameters.html).

**Comment by jtravan3** [comment]
Pull request https://github.com/Asymmetrik/node-fhir-server-core/pull/112 addresses this issue

**Comment by Robert-W** [comment]
Thanks @jtravan3, @jonterrylee and myself are going to try to go over as many PR's as we can today and get these things merged

**Comment by Robert-W** [comment]
Closing since the related PR is merged, thanks @jtravan3
