### ISSUE TITLE
Make npm package module

### ISSUE THREAD

**Issue by dominathan** [Asymmetrik/node-fhir-server-core#114]
### Do you want to request a feature, improve documentation, or ask a question?
Feature
### Are you reporting a bug?
No
**What is the current behavior?**
Have to reference github in package.json
**What is the expected behavior?**
Have npm package with versions
**What are the steps to reproduce?**

Are there plans to make this an npm package you all are going to maintain?  I am using a fork for our staging server implementation because I can't have changes going to master all willy nilly.  Do you want me to make one and have y'all be co-owners? Do you have other thoughts?

**Comment by Robert-W** [comment]
Hey @dominathan, thanks for putting this back on our radar. It has been on our roadmap for a while and is definitely something we have been wanting to do (amongst other things). After Amsterdam DevDays we got a little sidetracked but we are preparing a new tagged release and we can start publishing to npm with that one.

I asked our company admin for publish privileges under the Asymmetrik namespace so hopefully we'll get that soon and have something published before the end of this week.

**Comment by Robert-W** [comment]
So we should be getting this out very soon now. I have access and will be getting @jonterrylee access as well today, will keep you guys updated as soon as we have a release tagged.

**Comment by jonterrylee** [comment]
@dominathan 

We have published to NPM!!  Sorry for the holdup.  We have also tested on Aegis and passed.  If you notice any issues, please let us know!

[node-fhir-server-core](https://www.npmjs.com/package/@asymmetrik/node-fhir-server-core)

Thanks again
