### ISSUE TITLE
Asymmetrik/node-fhir-server-core with Microsoft SQL Server

### ISSUE THREAD

**Issue by lakshithaf** [Asymmetrik/node-fhir-server-core#130]
Currently i am trying use your Asymmetrik/node-fhir-server-core with Microsoft SQL Server is there any possibility to do that

**Comment by Robert-W** [comment]
@lakshithaf Absolutely, our server intentionally does not connect to any databases. We are in the process of updating our docs with more guides on how to do these things. Essentially though you just provide a service to `@asymmetrik/node-fhir-server-core`, and in that service, you connect to your database of choice, Microsoft SQL Server in this case, and run queries directly against that.

You can read up on profiles and how to use them here, https://github.com/Asymmetrik/node-fhir-server-core/wiki/Profile.  There are some examples of generically working with databases and how to configure things. It is a little out of date in terms of which profiles we support. We currently support everything listed [here](https://github.com/Asymmetrik/node-fhir-server-core/blob/master/src/constants.js#L1) under the RESOURCES property.

**Comment by Robert-W** [comment]
Closing this for now, if you have any further questions, please feel free to reopen and ask away !!

**Comment by lvlrSajjad** [comment]
> @lakshithaf Absolutely, our server intentionally does not connect to any databases. We are in the process of updating our docs with more guides on how to do these things. Essentially though you just provide a service to `@asymmetrik/node-fhir-server-core`, and in that service, you connect to your database of choice, Microsoft SQL Server in this case, and run queries directly against that.
> 
> You can read up on profiles and how to use them here, https://github.com/Asymmetrik/node-fhir-server-core/wiki/Profile. There are some examples of generically working with databases and how to configure things. It is a little out of date in terms of which profiles we support. We currently support everything listed [here](https://github.com/Asymmetrik/node-fhir-server-core/blob/master/src/constants.js#L1) under the RESOURCES property.

Another question.
Do we have to use a specific schema for database?
Or all that matters is we have to return a specific json schema through a specific service and the schema in the database doesn't matter?
Any suggestions for a SQL database?
