### ISSUE TITLE
Practitioner communication bug

### ISSUE THREAD

**Issue by kalihos** [Asymmetrik/node-fhir-server-core#140]
Hello,

I think there is a bug in the Practitioner entity, with the "communication" entry. I'm using as it's said on v3 FHIR specifications (https://www.hl7.org/fhir/practitioner-definitions.html#Practitioner.communication), and it loads nothing when casting to Practitioner class. I'm using exactly in the same way as in Patient's entity, and there it works well.

This is what I have just before casting:
"communication":[{"language":{"coding":[{"system":"http://hl7.org/fhir/ValueSet/languages","code":"es"}],"text":"es"},"preferred":true}]

And, after casting, I got a simple "communication":[{}]

It's not important, as it's not a mandatory field, but maybe it can be taken into account for the future.

Thank you very much.

**Comment by kalihos** [comment]
Hi Robert.

I downloaded it about two months ago (or less), so I suppose it's the
latest version.

Thanks to you!

**Comment by luan-dev** [comment]
Closing stale issue. Please open a new ticket if this is still a problem
