### ISSUE TITLE
Separating header Last-Modified from meta lastUpdated

### ISSUE THREAD

**Issue by kalihos** [Asymmetrik/node-fhir-server-core#145]
Hi.

I'm not sure if it's a bug, or not. I have a FHIR server with some entities. They returns a field named "Last-Modified" when the corresponding meta "lastUpdated" is defined in the service. Others are trying to access to my endpoint, but we are encountering different problems related to date formats. If I define meta lastUpdated in a correct format, Last-Modified header is automatically defined in the same way. But, for the third-party client from Microsoft, this is not correct, as one must be defined in an xs:dateTime format, but the other must be ISO with timezone. If I remove meta, header is also removed. They are linked in response.utils file:

res.set('Last-Modified', `${resource_json.meta.lastUpdated}`);

Is there any chance to get both dates separately, or both of them must be necessarily together?

Thanks in advance.

**Comment by kalihos** [comment]
Only in the case it were necessary for someone, only necessary change would be, in response.utils.js file:

res.set('Last-Modified', ${resource_json.meta.lastUpdated});

changing to...

res.set('Last-Modified', moment(`${resource_json.meta.lastUpdated}`).format('ddd, DD MMM YYYY HH:mm:ss Z'));

Previously including moment, of course:

const moment = require('moment-timezone');

**Comment by Robert-W** [comment]
Hey @kalihos,

Thanks for reporting this. I can take a look at this later today with Jon. We are trying to finalize a couple of things for an enterprise version of this server (hopefully we will have an announcement in the coming month or two  about that) so we have been a little preoccupied with that. However if this is a feature we can support or a bug that needs fixing we will see if we can't get it taken care of by version 1.3.1, which I hope to release by end of week.

**Comment by luan-dev** [comment]
Closing stale issue. Please open a new ticket if this is still a problem
