### ISSUE TITLE
Practitioner search by language doesn't work

### ISSUE THREAD

**Issue by kalihos** [Asymmetrik/node-fhir-server-core#146]
Hi,

Only to notify... If you query a practitioner by language (communication), it simply ignores that filter. In version v3. An example:

https://localhost:10000/3_0_1/Practitioner?given=dr&language=en

While "given" filter works fine, "language" is simply ignored.

Regards.

**Comment by Robert-W** [comment]
Hi @kalihos, I do not think we support that parameter in our current version. We are not manually creating these resources or parameter files, they are generated from structure definitions and for search parameters, we only support ones defined by the search parameters files. You can see the ones to a practitioner for STU3 here, http://hl7.org/fhir/stu3/practitioner.html#search.  

The next release will have support for custom arguments so you can pass in your own description of which arguments you want to support (2.0.0 may allow this to be further customizable by not just replacing the current args but by adding more to it).  We hope to get documentation up for how to do this soon.

**Comment by kalihos** [comment]
Yes, you're absolutely right. I mixed communication with language... sorry... It works perfect with communication (just tested now)!
