### ISSUE TITLE
Handling response

### ISSUE THREAD

**Issue by kalihos** [Asymmetrik/node-fhir-server-core#147]
I'm having troubles managing response in every operation I do. I know it's my fault, but I can't get a correct response, specially relevant when creating (for example, an appointment). I've been told by other people that this kind of entities should return back a Patient object when creating an object, not only the new ID for that patient. However, I get a blank "data" property, and instead I have a "data" property inside config sub-object. This is a problem, but it's bigger yet when I create an appointment. I have this response:

{"data":"","status":201,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"https://localhost:10000/3_0_1/Appointment","headers":{"Content-Type":"application/json+fhir;charset=UTF-8","Cache-Control":"no-cache","Accept":"application/json, text/plain, */*"},"data":{"objApp":{"resourceType":"Appointment","status":"pending","participant":[{"actor":{"reference":"Patient/295","display":"Prueba Prueba"},"required":"required","status":"accepted"},{"type":[{"coding":[{"system":"http://terminology.hl7.org/CodeSystem/v3-ParticipationType","code":"ATND"}]}],"actor":{"reference":"Practitioner/19","display":"Prueba Prueba"},"required":"required","status":"accepted"}],"slot":[{"reference":"Slot/1610146","display":"1610146"}],"start":"2019-02-11T12:10:00Z","end":"2019-02-11T12:20:00Z"}}},"statusText":"Created"}

As you see, data is still blank. transformRequest and transformResponse are both null, and my object "objApp" is inside data, but at a time inside config. And, what is worst, I haven't got my new ID anywhere. I'm finishing my service back to the controller with:

return resolve({ id: request.parameters.nuevaCita.value });

which I checked that got the correct value (an integer). I don't know what I'm doing bad...

Thank you very much in advance.

**Comment by kalihos** [comment]
Hi all.

Any update from this? I'm getting another strange thing related to this... When I create an appointment, this is correctly created, but, apart from previous notified error, I get a strange error on my server:

error: 404 '/3_0_1/3_0_1/Appointment/156471'

It seems like if, for some reason, version number were duplicated, and system were internally making this "duplicate" request to get the appointment detail in return just after creation. I don't know if FHIR server is really making this internal request to get back the appointment details. If so, maybe this is causing data is not back in the correct place, but into "config"...

Thank you very much.

**Comment by jonterrylee** [comment]
Hey @kalihos 

Sorry for the late response.  The FHIR spec doesn't specify to have to return the object that was created.  It does have to return the Content-Locaiton and ETag headers to link back to the created resource.  You can certainly return the created resource if you modify the responseUtils which it sounds like thats where you're having an issue.

Can you send me a snippet of your responseUtils for create? 

Also what do you have in your config for resourceServer?

**Comment by kalihos** [comment]
Hi @jonterrylee 

Thanks for your answer. This is my response.utils, though I don't remember to have modified it...

let handleCreateResponse = (res, base_version, type, results, options) => {
	let { id, resource_version } = results;
	let { resourceUrl } = options;

	if (resource_version) {
		res.set('Content-Location', `${path.join(resourceUrl, base_version, type, id, '_history', resource_version)}`);
		res.set('ETag', `W/"${resource_version}"`);
	}

	res.set('Location', `${base_version}/${type}/${id}`);
	res.status(201).end();
};

My config is:

const config = {
	profiles: {
		patient: {
			service: path.resolve('./backend/sql/patient.service'),
			versions: [ VERSIONS['3_0_1'] ]
		},
		appointment: {
			service: path.resolve('./backend/sql/appointment.service'),
			versions: [ VERSIONS['3_0_1'] ]
		},
		practitioner: {
			service: path.resolve('./backend/sql/practitioner.service'),
			versions: [ VERSIONS['3_0_1'] ]
		},
		slot: {
			service: path.resolve('./backend/sql/slot.service'),
			versions: [ VERSIONS['3_0_1'] ]
		},
		schedule: {
			service: path.resolve('./backend/sql/schedule.service'),
			versions: [ VERSIONS['3_0_1'] ]
		}
	},
	server: {
		port: portssl,
		corsOptions: {
			maxAge: 86400,
			origin: "*",
			methods: "GET,HEAD,PUT,PATCH,POST,DELETE",
			preflightContinue: false,
			optionsSuccessStatus: 204
		},
		ssl: {
			key: 'ssl/server.key',
			cert: 'ssl/server.crt'
		}
	},
	auth: {
		// This servers URI
		resourceServer: 'https://hl7integracion.kalihos.es'
	}
};

Thanks!!!

**Comment by kalihos** [comment]
Hi.

Any news from this? I only need to solve this problem this finish my server... hehe.

Thanks!

**Comment by sshah-asymmetrik** [comment]
Hi @kalihos,

I think I may have some suggestions to help resolve the issues you are having. The starting place to look is the services. I’m going to use the appointment.service.js from our node-fhir-server-mongo repo as a reference (https://github.com/Asymmetrik/node-fhir-server-mongo/blob/master/src/services/appointment/appointment.service.js).  Based on your previous comments, I believe that, like this example, you’re resolving the ‘id’ to send back to the controller, which is good. I think the problem you’re having is that the default implementation does not return the created resource, which is the behavior you’re seeking. If you want the ‘create’ action to also return the created resource to the user, you can add the resource itself to the resolved object:
`resolve({id, resource: appointment_resource})`

You can then edit your response.utils to send you the created resource, something like:
```
let handleCreateResponse = (res, base_version, type, results, options) => {
	let { id, resource, resource_version } = results;
	let { resourceUrl } = options;

	if (resource_version) {
		res.set('Content-Location', `${path.join(resourceUrl, base_version, type, id, '_history', resource_version)}`);
		res.set('ETag', `W/"${resource_version}"`);
	}

	res.set('Location', `${base_version}/${type}/${id}`);
	res.status(201).json(resource);
};
```

This solution may not be exact, but you should be able to get back the newly created resource so long as you ensure that you pass it back up from the service where it is created.

In regards to the created resource id, in your current setup, it won’t come back as part of the request body, but we can see that in the ‘handleCreateResponse’ method that the id (which should be ‘request.parameters.nuevaCita.value’) is being set as the ‘Location’ header. However, if you manage to get the whole resource back, it will contain its own id.

I hope this was helpful!

**Comment by sshah-asymmetrik** [comment]
Alternately, if all you need is the ID from the created resource, you can always just send back the ID as any part of the response. Currently it's being set as part of the 'Location' header, but you can do whatever you need to it in the response so that it comes back to you in a form that you can use.

**Comment by kalihos** [comment]
Thank you very much @sshah-asymmetrik . We'll try your solution and I'll feedback you.

Regards!

**Comment by kalihos** [comment]
It works! Thank you VERY much!

**Comment by sshah-asymmetrik** [comment]
Great! Happy to help!

**Comment by Aaqib-kk** [comment]
> It works! Thank you VERY much!

@kalihos i am facing the same issue on practitioner resource. How did you resolve the issue? please guide
