### ISSUE TITLE
Observation controller does not return links for search operation

### ISSUE THREAD

**Issue by StevenChin** [Asymmetrik/node-fhir-server-core#151]
### Are you reporting a bug?

Yes.

**What is the current behavior?**

When a search is performed on the Observation resource, the result does not contain the `link` property which contains urls for related resources.

Upon further investigation I noted that the search method in the observation controller was the only resource controller where the response utility was not being used to process the result (the metadata controller does this too but no additional processing is done in this instance). Was this intentional or did you guys just miss this when updating the resource controllers?

**What is the expected behavior?**

When a search is performed on the Observation resource, the result should contain the `link` property which contains the url for the search results:

```bash
GET /3_0_1/Observation

{
  "resourceType": "Bundle",
  "type": "searchset",
  "link": [
    {
      "relation": "self",
      "url": "http://localhost:3000/3_0_1/Observation"
    }
  ],
  "total": 0,
  "entry": []
}
```

**What are the steps to reproduce?**

```bash
GET /3_0_1/Observation

{
  "resourceType": "Bundle",
  "type": "searchset",
  "total": 0,
  "entry": []
}
```

**What OS are you using and what version of node.js and @asymmetrik/fhir-server-core are you running?**

OS: `Mac OS 10.14 (Mojave)`
Node: `10.14.2`
@asymmetrik/fhir-server-core: `1.2.0`

**Comment by sshah-asymmetrik** [comment]
@StevenChin 

Good catch!

It looks like you are correct, the observation resource was missed when we updated the controllers. I've created a pull request to remedy this resource. We're planning on a new release that should make the controllers more uniform. 

It should be noted that if you're also using our node-fhir-server-mongo, that the observation service is also a little out of date. We appreciate you bringing this to our attention. If you'd like to keep your development moving forward without having to wait for our review process, feel free to change your code locally. You should be able to achieve the desired results by mirroring the structure in the patient resource's controllers/services.

Thanks,
-Sumeet

**Comment by Robert-W** [comment]
Closing this since we merged a fix, if you are still experiencing this issue please feel free to re-open or create a new PR.
