### ISSUE TITLE
Feature request to add $everything operation on Patient and Encounter resources

### ISSUE THREAD

**Issue by neethu2092** [Asymmetrik/node-fhir-server-core#152]
https://www.hl7.org/fhir/patient-operation-everything.html
https://www.hl7.org/fhir/operation-encounter-everything.html

**Comment by dominathan** [comment]
This functionality already exists. We will need to update the wiki to show how but...

You can do this by generating your own operation.   In your config.
```js
	patient: {
			service: path.resolve('./YOUR_PATH'),
			versions: [VERSIONS['3_0_1']],
			operation: [
				{
					name: 'everything',
					route: '/$everything',
					method: 'GET',
					reference: 'https://www.hl7.org/fhir/patient-operation-everything.html'
				},
                                 {
					name: 'everything-by-id',
					route: '/:id/$everything',
					method: 'GET',
					reference: 'https://www.hl7.org/fhir/patient-operation-everything.html'
				},
 
			]
		}
```
Then make a function name in your file that matches the camelcased version of the name in the operation.  

Hope that helps .

**Comment by dominathan** [comment]
@neethu2092 I added documentation here
https://github.com/Asymmetrik/node-fhir-server-core/wiki/Operations.

**Comment by neethu2092** [comment]
@dominathan This was exactly what I was looking for. Thank you for adding it to the documentation.
