### ISSUE TITLE
Generating StatusCode 404

### ISSUE THREAD

**Issue by dominathan** [Asymmetrik/node-fhir-server-core#153]
## Question about generating a 404

**What is the current behavior?**
Let's say I have a Medication Resource and I have this function to get a medication by ID

```js
module.exports.searchById = (args, context, logger) => {
	logger.info(`Getting medication with ID: ${args.id}`)
	return new Promise(async (resolve, reject) => {
		try {
			let data = await getDrug(args.id)
			const resp = JSON.parse(data.body) // WHAT DO I DO WHEN RESOURCE NOT FOUND
			resolve(resp)
		} catch (err) {
			reject(err)
		}
	})
}
```

What is the best way to return a 404 to the user when `getDrug` returns nothing? I would like to generate an OperationOutcome, but I don't have access to set the statusCode, do I?  Is this something I need to make a pull request for? Or do you handle it a different way
@jonterrylee

**Comment by dominathan** [comment]
@Robert-W How do you handle 404 errors you want to generate like above in your implementation of node-fhir-server-core? Or anyone else?

**Comment by jonterrylee** [comment]
Hey @dominathan 

Sorry we've been slammed this week.  We've went back and forth on this one for a while.  We've ultimately decided that returning a 404 can give away too much information about what patients are in the system.  We felt that it might be safer to just return no results vs 404.

Given that, we are in the midst of releasing version 2.0.  It will have some major changes and we are trying to make it more flexible.  @Robert-W and I will try to think of the best way to accomplish this.  Possible adding a status code to response utils that you can pass back from the service.

**Comment by dominathan** [comment]
I can see how that makes sense for certain use cases. But, let's say someone is searching for a Medication with `code=http://rxnorm.com|234324` . I don't believe that should be a 200 empty response.  

Long story short, I think the framework shouldn't care about dictating the status code.  It should allow for an override by implementer if desired.  What are your thoughts on that?

**Comment by jonterrylee** [comment]
We're definitely open to allow overrides.

We're thinking about keeping promise resolve tied to response utils and making rejects more customizable (you return the operation outcome and code)?

**Comment by jonterrylee** [comment]
@dominathan If you have the bandwidth and don't mind, it would be greatly appreciated!!!!

**Comment by dominathan** [comment]
#154
