### ISSUE TITLE
R4 Timeline

### ISSUE THREAD

**Issue by dominathan** [Asymmetrik/node-fhir-server-core#156]
What is the expected R4 release timeline?

**Comment by jonterrylee** [comment]
@dominathan currently it's part of the 2.0 release.  We hope to have that merged in soon.

https://github.com/Asymmetrik/node-fhir-server-core/tree/feat/version_2_0_0

If you need this for 1.x, let us know.  We can put that in.

**Comment by Robert-W** [comment]
per discussion [here](https://github.com/Asymmetrik/node-fhir-server-core/pull/154), we will add a task to back port R4 to the current version and publish a new version. probably 1.4.0, when a PR is available, I will link it here and include some notes about how to get started using them (it will be a simple config update :))

**Comment by Robert-W** [comment]
Started work on this branch, [feat/r4-resources](https://github.com/Asymmetrik/node-fhir-server-core/tree/feat/r4-resources), should have something merged by early/mid next week. We need to do some more testing to make sure arguments are properly concatenated, metadata is good, and all configurations still work

**Comment by Robert-W** [comment]
This is slightly delayed, due to an issue described here, https://github.com/Asymmetrik/node-fhir-server-core/pull/157#issuecomment-477168276, once we resolve this with our internal code generator the PR should be good to go and we can merge it :)

**Comment by dominathan** [comment]
Please me know when 1.4.0 is out with custom errors.  Let me know if you need help with other items.
@Robert-W

**Comment by Robert-W** [comment]
Thanks @dominathan, will do. I have fixed the issue with the generator. We actually found out that there were many resources missing fields related to the issue described in the other PR, which have all been addressed. Once the team signs off on it we should be good to go.

**Comment by Robert-W** [comment]
MERGED !!!!!!
