### ISSUE TITLE
Creating custom profile

### ISSUE THREAD

**Issue by s0d-d** [Asymmetrik/node-fhir-server-core#160]
Do you want to request a feature, improve documentation, or ask a question?
Asking a question
----------------------------------------------------------------------------------------
Hello, I am new to NodeJS and am having trouble creating a custom profile.
Could anyone tell me how to create a profile and when creating new resources how can I check validation with my profile?

**Comment by Robert-W** [comment]
Hey @s0d-d,

Thanks for asking. Unfortunately this library does not expose an API that supports adding custom profiles very easily. We are working on some services to cover that use case now and hope to have them ready soon. If you would like, you could send an email to our technical team so they can try to help you with that, fhir-dev@asymmetrik.com.
