### ISSUE TITLE
The deprecated __resourceType still referenced in controllers.js

### ISSUE THREAD

**Issue by swishstar** [Asymmetrik/node-fhir-server-core#161]
### Do you want to request a feature, improve documentation, or ask a question?
No
### Are you reporting a bug?
Yes

**What is the current behavior?**
When PUTing a new Patient resource following a fresh install and the instructions at https://github.com/Asymmetrik/node-fhir-server-mongo, I get an error: 
```'resourceType' expected to have value of 'undefined', received 'Patient'```

**What is the expected behavior?**
A new Patient resource to be added.

**What are the steps to reproduce?**
PUT a new Patient resource following a fresh install and the instructions at https://github.com/Asymmetrik/node-fhir-server-mongo

**What OS are you using and what version of node.js and @asymmetrik/fhir-server-core are you running?**
$ node -v
v10.15.3
fhir-server-core: 1.4.0

Note: See https://github.com/Asymmetrik/node-fhir-server-core/pull/157#issuecomment-476221774 for comment about same issue during last PR#157. I tracked down issue to https://github.com/Asymmetrik/node-fhir-server-core/blob/master/src/server/profiles/patient/patient.controller.js#L137. Of course, the rest of the profile controllers have this same issue from a quick grep.

**Comment by swishstar** [comment]
Oh yeah... https://github.com/Asymmetrik/node-fhir-server-core/blob/master/src/server/profiles/patient/patient.controller.js#L140 is supposed to have the fix too.

**Comment by Robert-W** [comment]
Hey @swishstar, thanks for reporting this. I thought we caught all these but looks like a few slipped through.  Looks like there are definitely a few places where this is still present in all the controllers. We are a little preoccupied today so I do not think we can get something out today, but I'll bring it up with the team.

If anyone has bandwidth to try to fix this submit a PR, this should be a really simple patch (find and replace __resourceType with resourceType in controllers).

**Comment by swishstar** [comment]
@Robert-W : You're welcome. I was going to clone the repo this morning to fix because I didn't have time yesterday. Assuming the testing went OK. Thanks for doing it so quick and you saved me from any possible rabbit holes I might have went down in the process. I'm going to still clone it just in case I see other places to contribute.

**Comment by Robert-W** [comment]
No problem, let us know if you encounter any other issues.  If you want to also contribute that would be great as well !! We were in the midst of preparing a 2.0.0 release and are currently implementing some enterprise services so we have been a little busy lately.
