### ISSUE TITLE
How to customize generated capability statement? 

### ISSUE THREAD

**Issue by aaburgos4** [Asymmetrik/node-fhir-server-core#166]
@Robert-W is there any way to configure what information gets returned by the CapabilityStatement when hitting the /metadata route?

**Comment by Robert-W** [comment]
Hey @aaburgos4, yes there is. I haven't had a chance to update the docs to show that capability yet but in the meantime, if you check out this pull request, https://github.com/Asymmetrik/node-fhir-server-core/pull/128 , you can see how it was added. You essentially provide a `statementGenerator` service to the config that mimics https://github.com/Asymmetrik/node-fhir-server-core/blob/master/src/server/metadata/capability.4_0_0.js and the app should pull it in. Your config should look something like this:

```javascript
module.exports = {
        // customStatementGenerator needs to export the same two methods as
        // the capability.4_0_0.js linked above
        statementGenerator:  customStatementGenerator,
	server: {
		port: 3000,
		corsOptions: {
			maxAge: 86400,
			methods: 'GET,HEAD,PUT,PATCH,POST,DELETE',
		},
	},
	logging: {
		level: 'debug',
	},
	profiles: {
		Appointment: {
			service: './src/server/profiles/service.mock.js',
			versions: [VERSIONS['3_0_1']],
		},
        }
}
```

There is also an option to customize the resource as it shows up in the capability statement, just be careful to make sure you stay compliant with what it returns. For that, you just add a `makeResource` property to your profile configuration.

You can see examples of how all these work by looking at the https://github.com/Asymmetrik/node-fhir-server-core/blob/master/src/server/metadata/metadata.test.js file.

**Comment by Robert-W** [comment]
I'll add a task to update the docs with an example so this is more clear in the future.

**Comment by aaburgos4** [comment]
@Robert-W Thank you very much, I was able to generate the custom statement. I also don't mind submitting a PR to update the documentation as well :).

**Comment by Robert-W** [comment]
That would be great.  We currently have all our docs in a wiki, which unfortunately has no PR process or version control. I have a local branch which is moving everything out of there into a docs section which will allow us to have version control on our docs (we need to do this before we release version 2.0 anyway).

Let me get that PR up and then after that if you could add a page that would be great.

**Comment by Robert-W** [comment]
Hey @aaburgos4, we have merged a PR with a docs folder in it. I added a placeholder for it here, https://github.com/Asymmetrik/node-fhir-server-core/blob/master/docs/CustomCapability.md, if you still have time to contribute some docs we would love to have the help.
