### ISSUE TITLE
Missing R4 constant + profile?

### ISSUE THREAD

**Issue by mihaixyx** [Asymmetrik/node-fhir-server-core#168]
Noticed that some R4 resources, for example ServiceRequest is missing from the file src/constants.js and doesn't have a profile inside src/server/profiles/ , is that something you might have missed, is it planned for further patches or am I missing something?

**Comment by Robert-W** [comment]
Hi @mihaixyx, thanks for pointing this out. We have support for this in our 2.0 branch which we hope to release soon, but we can probably add it back here as well fairly soon. 

This version has a lot of manual updates and our 2.0 has a lot more automated updates, so this was just a case of us developing both versions side by side and not getting to backport some of the new R4 capabilities yet.

**Comment by Robert-W** [comment]
2.0.0 is released now and this is supported.  If you cannot upgrade, we can retro fit it but it may not happen til after dev days (June 10 -12) unless someone else can contribute. We have a few things we are trying to wrap up before then and will be a little busy until after that.
