### ISSUE TITLE
What's the status of events(auditevent and provenance) feature in v2.0.3 ?

### ISSUE THREAD

**Issue by navndn** [Asymmetrik/node-fhir-server-core#189]
### Do you want to request a feature, report a bug, or improve documentation?
Feature request / documentation

[Server configuration doc](https://github.com/Asymmetrik/node-fhir-server-core/blob/master/docs/ServerConfiguration.md#eventsauditevent) here says event handlers are supported but I couldn't find any documentation on what events are supported or how to emit custom events from inside service methods or so.

I came across this [events PR](https://github.com/Asymmetrik/node-fhir-server-core/pull/30) from last year but it looks like current code base of server-core-2.0.3 has diverged significantly from that..  

I want to create auditevents for all write operations. Any suggestions on how to approach this ?
@Robert-W @jjosef 

I'm using 
Node.js: v10.15.3
node-fhir-server-core: 2.0.3

Thanks!

**Comment by Robert-W** [comment]
Hi @navndn,

This is something we were originally intending to setup. The original PR setup a framework for triggering those events but never fully integrated it and this is something that definitely needs to be updated in the documentation.

Currently, the approaches are more of a custom setup, but still not difficult at all. I'll make sure to add fixing the documentation and discussing a better way to do this in the future in our next sprint.

But. to do this today, you have two options. First, add a line into your services to do the write. We talk about setting these up in https://github.com/Asymmetrik/node-fhir-server-core/blob/master/docs/ConfiguringProfiles.md#create. You can add some code for your create operation so in theory, it would look something like this.

```javascript
const { resolveSchema } = require('@asymmetrik/node-fhir-server-core');
// In patient service
module.exports.create = async (args, context) => {
        // context.req contains the express request object, so you can get any
        // information you need for the audit event from there
        let AuditEvent = require(resolveSchema(args.base_version, 'auditevent'));
	let Patient = require(resolveSchema(args.base_version, 'patient'));
	let doc = new Patient(args.resource).toJSON();
        let event = new AuditEvent(<insert audit info here>).toJSON();
	let results = await db.patients.insertOne(doc);
        let eventresults = await db.auditevents.insertOne(event);

	return {
		id: results._id,
		// This is optional if you support versions
		resource_version: 1,
	};
};
```

The downside to this approach is you need to implement this in every service. The other option is to add a custom route and inspect each request, if the request is a create, update, or delete operation, then save your audit/provenance event. You can see an example of how to custommize the setup process of our server in our access control docs here, https://github.com/Asymmetrik/node-fhir-server-core/blob/master/docs/AccessControl.md#how-to-customize. Here is a pseudocode example more specific to your use case:

```javascript
const { Server, resolveSchema } = require('@asymmetrik/node-fhir-server-core');

let server = new Server(config)
	.configureMiddleware()
	.configureSession()
	.configureHelmet()
	.configurePassport();

// Write your event handler here, you will need some
// logic to make sure it is a write operation. Also,
// this MUST be implemented before setting error
// routes. Due to how express does routing and how this
// project is setup, the error routes will catch all requests
// and return a 500 or 404.
server.app.use(function (req, res, next) {
	// Determine the version the request is targeting
        let base_version = req.params.base_version;
        // Load an event resource
        let AuditEvent = require(resolveSchema(base_version, 'auditevent'));
        let event = new AuditEvent(<event-json-here>);
        
        try {
          // Write to your database
          await db.auditevents.insertOne(event);
        } catch (err) {
          next(err);
        }
});

server.setPublicDirectory()
	.setProfileRoutes()
	.setErrorRoutes();

// Finally start the server
server.listen(3000);
```

**Comment by navndn** [comment]
Hi @Robert-W , 
Thanks for the detailed response! I was also thinking on similar lines. Btw, on 2nd approach, isn''t it better to attach event handler middleware after resource operations i.e after .setProfileRoutes() ?

**Comment by Robert-W** [comment]
If you placed it after that it would not ever get invoked. The 2nd method uses it as generic middleware without specifying a route, so all requests use it. When we set call `setProfileRoutes()`, we are invoking something like this:

```javascript
app[route.type]( // app.get or app.post
  profileRoute, // something like /:base_version/patient
  cors(corsOptions),
  versionValidationMiddleware(profile),
  sanitizeMiddleware(route.args),
  authenticationMiddleware( config ),
  sofScopeMiddleware({ route, auth: config.auth, name: key }),
   // invoke our controller which calls your service
  loadController(lowercaseKey, route.interaction, profile.serviceModule),
);
```

So if a request matches the above endpoint, it only hits middleware and controllers defined in this chain.  Once express matches a route, it won't invoke any other matching routes. So even though we specified generic middleware that should in theory apply to all routes, because express already found a match, it won't invoke our middleware.

**Comment by navndn** [comment]
Got it, Thanks

**Comment by Robert-W** [comment]
No problem, let me know if I can help with anything else. I am going to leave this open as a reminder to the team to bring this up in our next sprint discussion so we can update documentation and potentially implement an easier method for this.

**Comment by lokeshgs87** [comment]
Hi can you please help me in creating the auditevent info ? for example i am changing it in organization? how do i create the audit event info?

**Comment by luan-dev** [comment]
Closing stale issue. Please open a new issue if this was incorrect
