### ISSUE TITLE
Incorrect reference in 4_0_0 schema for Timing

### ISSUE THREAD

**Issue by jjosef** [Asymmetrik/node-fhir-server-core#206]
https://github.com/Asymmetrik/node-fhir-server-core/blob/98d74f6538fddf77868e0b4ea85ba5628955c471/src/server/resources/4_0_0/schemas/timing.js#L90

```js
		Object.defineProperty(this, 'repeat', {
			enumerable: true,
			get: () => this.__data.repeat,
			set: value => {
				if (value === undefined || value === null) {
					return;
				}

				let Element = require('./element.js');
				this.__data.repeat = new Element(value);
			},
		});
```

this is requiring the wrong thing, should be:

```js
const TimingRepeat = require('./timingrepeat.js');
this.__data.repeat = new TimingRepeat(value);
```

will submit a PR in a few

**Comment by sshah-asymmetrik** [comment]
Good catch! We'll get your corrective PR merged and make a ticket to look into the underlying cause. Thanks!
