### ISSUE TITLE
Enabling SSL throws error

### ISSUE THREAD

**Issue by keerthivasan-r** [Asymmetrik/node-fhir-server-core#208]
### Do you want to request a feature, report a bug, or improve documentation?
I would like to report a bug in enabling SSL
### If you are reporting a bug?

**What is the current behavior?**
When we pass **ssl** configuration to server,

```
server: {
	port: 4000,
        ssl: {
		key: __dirname+'/configs/ssl/key.pem',
		cert: __dirname+'/configs/ssl/cert.pem'
		},
	},
```
It throws the error below

> Cannot use 'in' operator to search for 'includeSubdomains'

in hsts/index.js

**What is the expected behavior?**

The server should be enabled with SSL with provided certificate and key pair

**What are the steps to reproduce?**

We can reproduce it by just passing ssl config into the server configuration

**What OS are you using and what version of node.js and @asymmetrik/node-fhir-server-core are you running?**
Node 8.11 and @asymmetrik/node-fhir-server-core@2.0.5

**Comment by keerthivasan-r** [comment]
I think i have figured out where the bug is

In server.js, we have the env object set like this

```
this.env = {
IS_PRODUCTION: !process.env.NODE_ENV || process.env.NODE_ENV === 'production',
USE_HTTPS: server.ssl && server.ssl.key && server.ssl.cert,
};
```
But, it should be like this

```
this.env = {
IS_PRODUCTION: !process.env.NODE_ENV || process.env.NODE_ENV === 'production',
USE_HTTPS: server.ssl.key && server.ssl.cert && server.ssl,
};
```

**Comment by ggerade** [comment]
Hi Keerthivasan, I pretty much stumbled on this while catching up on goings on in the repo... Anyway, the change you made doesn't look to me like it'd have any affect as server.ssl is already in the boolean expression. Maybe I'm missing something...

**Comment by keerthivasan-r** [comment]
It is not just about the checking of server.ssl in the boolean expression. The problem is the data that gets assigned back to the property. The value of USE_HTTPS gets the value of server.ssl.cert instead of server.ssl. That creates the problem, when it is used by helmet config in the next step. To be clear, `USE_HTTPS` doesn't expect a boolean value, it expects an object that contains the value of key and certificate. Hope you understand.

**Comment by ggerade** [comment]
It make sense now Keerthivasan thanks! Maybe it'd be a bit more obvious/readable if it were something like: `(server.ssl && server.ssl.key && server.ssl.cert) ? server.ssl : undefined`

**Comment by keerthivasan-r** [comment]
Yup! That's perfect. In multiple places, I saw this way of setting values. so, i just followed. I will make that change and update the PR

**Comment by keerthivasan-r** [comment]
I have just updated the PR #211
