### ISSUE TITLE
[feat] Prevent js file use from server configuration object

### ISSUE THREAD

**Issue by Ahryman40k** [Asymmetrik/node-fhir-server-core#212]
Hi, 

I would like to propose a new feature to the _node-fhir-server-core_.

Documentation describe how a config object should be constructed and provided to asymmetrik server initialization

```Javascript
let config = {
	profiles: {
		composition: {
			service: `${__dirname}/services/composition.service.js`,
			versions: [
				'4_0_0'
			],
			metadata: `${__dirname}/metadata/composition.metadata.js`
		}
	}
};
let server = asymmetrik.initialize(config);
```
As we are using typescript, providing a Javascript file path can be a difficult task, mainly in tests where code isn't transpiled. 
So I would like to provide improvements  regarding the configuration object. 
Because I were doing experiments with configuration, I saw an error was thrown when 'service' path in configuration object is empty. Exception occurs in method '_verifyAndLoadProfiles_' from '_server.js_' file. With the following code:

```Javascript
try {
	profiles[name].serviceModule = typeof service === 'string' ? require(path.resolve(service)) : service;
} catch (err) {
	message = `Invalid ${name} configuration. ${err.message}`;
}
```

I noticed that if type of '_service_' isn't a string then object is stored in _serviceModule_ property instead of loading a module from its path. 
Because metadata isn't a required property the same mechanism doesn't happen during the validation process.

So I was wondering if the same behaviour exists for '_metadata_' property. 
In the file params.utils.js, method '_getSearchParameters_' load our metadata module from the provided path. We can see these few lines of code: 

```Javascript
if (customArgsModule) {
       let paramsAsArray = require(String(customArgsModule)).makeResource(
	        Object.assign({}, { base_version: version, key: lowercaseProfileName }),
		logger,
	).searchParam;
   [...]
```
Provided metadata module is loaded from its path then call the '_makeResource_' method.
So If I understood clearly the logic here, I could test type of '_customArgsModule_' then load module if it's a path else simply use object ? I mean something like:  
```Javascript
const makeResourceFn = typeof customArgsModule === 'string' ? require(String(customArgsModule)).makeResource : customArgsModule.makeResource;

let paramsAsArray = makeResourceFn(
	Object.assign({}, { base_version: version, key: lowercaseProfileName }),
	logger,
).searchParam;
    [...]
```

Do you agree with my analysis ?
Are you ok to add surch feature ? If so can I create a Pull request ?

Best regards, 
Ahry

**Comment by michelekorell** [comment]
It is very useful, mostly when it is used inside a TypeScript project!

**Comment by zeevosec** [comment]
See https://github.com/Asymmetrik/node-fhir-server-core/pull/213#issuecomment-562153154
