### ISSUE TITLE
Elliptic Timing Attack

### ISSUE THREAD

**Issue by awatson1978** [Asymmetrik/node-fhir-server-core#215]
### Do you want to request a feature, report a bug, or improve documentation?
Reporting a security defect.

Hello, Linux Community Bridge is reporting a Timing Attack based on the `elliptic` library, which is included in `node-fhir-server-core` based on the `jwk-to-pem` library which uses it as a dependency. 

![Screen Shot 2019-12-04 at 12 42 03 PM](https://user-images.githubusercontent.com/675910/70171789-0f3fd080-1695-11ea-833d-a77f7fe52e31.png)

I've confirmed that its' `jwk-to-pem` pulling in [elliptic:^6.2.3](https://github.com/Brightspace/node-jwk-to-pem/blob/master/package.json#L35), and have reported the issue to them in brightspace/node-jwk-to-pem#33

Possible resolutions include removing `jwk-to-pem` from `node-fhir-server-core`, or working with Brightspace to get their library patched and then updating the FHIR Server.

**Comment by j3parker** [comment]
We merged a fix submitted by a community member: https://github.com/Brightspace/node-jwk-to-pem/pull/32

Sorry for the delay on this!
