### ISSUE TITLE
ONC FHIR Challenge Vulnerability: Modify Token Properties

### ISSUE THREAD

**Issue by Robert-W** [Asymmetrik/node-fhir-server-core#22]
Given a valid access token, client id, and client secret. The valid token is able to be decoded, modified, and resigned. Once it is resigned, it can be sent back into the server and the server still thinks the token is valid.

This was used to modify scopes and extend the expiration time of a token.

**Comment by jonterrylee** [comment]
Mock service has been removed.  The default validation included will send the token to the Auth server for validation.
