### ISSUE TITLE
Bug: Create method won't return values

### ISSUE THREAD

**Issue by aaburgos4** [Asymmetrik/node-fhir-server-core#222]
I am creating a resource and trying to return the ID from my database once it's created. The [(docs)](https://github.com/Asymmetrik/node-fhir-server-core/wiki/Profile#create) mention that it should be able to return the `id` and the `resource_version`, but instead I receive an empty response. 

```
exports.create = async (params, { req }) => {
  return {
    id: 'test',
    resource_version: '1'
  };
};
```

**Comment by aaburgos4** [comment]
Closing after seeing in the source code that this returns a 201.

**Comment by ZuSe** [comment]
@aaburgos4 

Why is 201 for u ok? I think returning the created object or at least the id would be more RESTlike and help client developers a lot.

**Comment by bhargavaprabu** [comment]
@aaburgos4 Same issue for me! Receiving response as empty string ""
