### ISSUE TITLE
{"message":{"resourceType":"OperationOutcome","issue":[{"severity":"error","code":"not-found","details":{"text":"Invalid url: /4_0_0/authorize"}}]},"level":"error"}

### ISSUE THREAD

**Issue by rahutwr33** [Asymmetrik/node-fhir-server-core#226]
{"message":{"resourceType":"OperationOutcome","issue":[{"severity":"error","code":"not-found","details":{"text":"Invalid url: /4_0_0/authorize"}}]},"level":"error"}

**Comment by sychus** [comment]
Hi rahutwr33,

The url you are trying to access does not exist. What are you trying to perform?

Cheers!
Hugo

**Comment by rahutwr33** [comment]
> Hi rahutwr33,
> 
> The url you are trying to access does not exist. What are you trying to perform?
> 
> Cheers!
> Hugo

working on a healthcare product.it has been fixed.so closing the issue.Thanks
