### ISSUE TITLE
Has anyone begun work to implement support for 4.0.1?  Especially for the CMS Final rule?

### ISSUE THREAD

**Issue by matthewjcable** [Asymmetrik/node-fhir-server-core#239]
### If you are reporting a bug?

**What is the current behavior?**

**What is the expected behavior?**

**What are the steps to reproduce?**

**What OS are you using and what version of node.js and @asymmetrik/node-fhir-server-core are you running?**

**Comment by zeevosec** [comment]
Not that I know of. Do you have documentation on the CMD Final rule I could check out?

**Comment by matthewjcable** [comment]
High-level details are here: [https://www.cms.gov/Regulations-and-Guidance/Guidance/Interoperability/index](https://www.cms.gov/Regulations-and-Guidance/Guidance/Interoperability/index)

Links to specs are about 1/3 of the way down the page.

**Comment by mgramigna** [comment]
I would like to follow up on this. Is there any planned support for FHIR 4.0.1?

**Comment by hank-lenzi** [comment]
No answer means this should eventually be forked, in order to support 4.0.1

**Comment by mgramigna** [comment]
I opened https://github.com/Asymmetrik/node-fhir-server-core/pull/303 for this

**Comment by luan-dev** [comment]
4.0.1 support has been added
