### ISSUE TITLE
ONC FHIR Challenge Vulnerability: Token creation and validation

### ISSUE THREAD

**Issue by Robert-W** [Asymmetrik/node-fhir-server-core#24]
Two separate issues here but can be fixed with a similar patch. The oauth server used in this repo as an example was not a fully implemented oauth server. Replacing our mock oauth server with a fully secured oauth server should remediate both the following issues, but they need to be verified independently.

First issue is that with a client id and client secret, tokens can be self generated without going to an oauth server, and then used to access resources.

Second issue is that a client secret is not required to request an auth token when the client is "trusted".

**Comment by jonterrylee** [comment]
mock services has been removed
