### ISSUE TITLE
Support multiple auth strategies

### ISSUE THREAD

**Issue by ZuSe** [Asymmetrik/node-fhir-server-core#240]
### Do you want to request a feature, report a bug, or improve documentation?
Yes

I haven't found anything in docs that's why I am asking here.
But we would need to support multiple Auth Strategies at the same time.
OIDC for the patients, but also sth. like Api-Keys for Server-2-Server and Cert-Auth for Doctors. 
Is there the plan to add such functionality to the project?

**Comment by zeevosec** [comment]
Hi 👋

Can you elaborate on what this would look like in regards to `node-fhir-server-core`? How would the library API change?

**Comment by alejosv** [comment]
This should be resolved completely that requirements: [Access Control](https://github.com/Asymmetrik/node-fhir-server-core/blob/20391b56140ad9f2589b0598d67ba4de96202357/docs/AccessControl.md)
