### ISSUE TITLE
Invalid package name "@asymmetrik/node-fhir-server-core"

### ISSUE THREAD

**Issue by kkostia** [Asymmetrik/node-fhir-server-core#242]
I get a problem while try to install package with a following comand : "npm i @asymmetrik/node-fhir-server-core" and recive such error : "
npm i @asymmetrik/node-fhir-server-core
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@asymmetrik%2fnode-fhir-server-core - Not found
npm ERR! 404
npm ERR! 404  '@asymmetrik/node-fhir-server-core@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
"
OS : Windows 10
node version: v12.18.1
npm version: 6.14.5

**Comment by sychus** [comment]
Hi kkostia,

I tried to reproduce your error but it was not possible. In my case this is the output of the command execution.

**_npm i @asymmetrik/node-fhir-server-core
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated lodash.isarray@4.0.0: This package is deprecated. Use Array.isArray.
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN testasy@1.0.0 No description
npm WARN testasy@1.0.0 No repository field.

@asymmetrik/node-fhir-server-core@2.0.10
added 799 packages from 485 contributors and audited 799 packages in 124.845s
found 0 vulnerabilities_**

OS: Linux Mint 20
node version: v12.0.0
npm version: 6.9.0

Cheers!
