### ISSUE TITLE
Unable to require bundleEntry schema

### ISSUE THREAD

**Issue by tferullo** [Asymmetrik/node-fhir-server-core#266]
### Do you want to request a feature, report a bug, or improve documentation?
bug 
### If you are reporting a bug?

**What is the current behavior?**
after upgrading to 2.2.0 this doesn't work:
```js
const BundleEntry = FHIRServer.resolveSchema('4_0_0', 'bundleentry');
```

**What is the expected behavior?**
that it is exported from the index.js file in the resources directory

**What are the steps to reproduce?**
Try resolving the bundleEntry schema as shown above

**What OS are you using and what version of node.js and @asymmetrik/node-fhir-server-core are you running?**

**Comment by zeevosec** [comment]
Good catch. I'll be fixing this and publishing a new version today.

**Comment by zeevosec** [comment]
@tferullo Try upgrading to 2.2.3
