### ISSUE TITLE
Simple syntax error

### ISSUE THREAD

**Issue by dreamofsnail** [Asymmetrik/node-fhir-server-core#318]
### Do you want to request a feature, report a bug, or improve documentation?
Hi
It was a simple syntax error, so I registered the PR first.
https://github.com/Asymmetrik/node-fhir-server-core/pull/317
(This is what I confirmed during the PR registration process reflected in 'node-fhir-server-mongo' recently)
please check.

**Comment by luan-dev** [comment]
Hi @dreamofsnail,

Thanks for submitting the PR! I did some investigating on the issue and it seems that your fix did not pass all the unit tests. I believe that the syntax might have been intentional.

If you have more info regarding the error, I'll be glad to look into it some more
