### ISSUE TITLE
Getting Started doesn't get started

### ISSUE THREAD

**Issue by mcdemarco** [Asymmetrik/node-fhir-server-core#58]
### Do you want to request a feature, improve documentation, or ask a question?

This is regarding the Getting Started page of the wiki documentation. 

### Are you reporting a bug?

**What is the current behavior?**

The Getting Started page (https://github.com/Asymmetrik/node-fhir-server-core/wiki/Getting-Started) says to create a couple of files (without saying where to put them), and then look at the results on localhost:3000, but there is no instruction that actually starts a server on localhost.

**What is the expected behavior?**

Apparently, a startup step for the server should be included in the instructions.

**What are the steps to reproduce?**

Follow the instructions on the wiki page as of the 6th revision.

**What OS are you using and what version of node.js and @asymmetrik/fhir-server-core are you running?**

MacOS 10.12.6
Node v.10.5.0
Yarn v.1.7.0
@asymmetrik/fhir-server-core - presumably the yarn command provided installed master

**Comment by mcdemarco** [comment]
It is now possible to start up the app by following the Getting Started page, thanks, and the one endpoint mentioned at the end works.  However, the Patient endpoint created there doesn't work because authentication is not set up.  (It's also not clear from the documentation what an EHR AuthZ server is or whether a regular OAuth2 server will suffice for development purposes.)

**Comment by Robert-W** [comment]
Hey @mcdemarco, thanks and glad that worked for you. We do have some details on the authentication piece in our Wiki but nothing on standing up your own OAuth server.  We are close to merging our latest round of updates which added the ability to run the server without auth, note that this should only be done for local development but can be helpful for getting things setup. 

I'll review this with our team when they all come in today and get back to you as soon as possible.

**Comment by jonterrylee** [comment]
Hey @mcdemarco, thanks again trying this out.  In general, you need to supply your own oAuth server.  There's a few on github that you can check out and I can point you to one that we've used.  

If you're using the develop branch, we've added the option to skip validation for development and testing.   In your test config, just comment out the auth {... section.

Another way to skip validation is to set your node_env=test.  

Hope this helps, let me know if you have any questions or suggest any changes.  We're open for collaboration.

Thanks

**Comment by mcdemarco** [comment]
Thanks!  Using the develop branch without an auth section worked, although the resourceServer URL is in there so I put that back (while trying to figure out why the metadata stopped working).  That didn't seem to break non-authentication, though perhaps it should have.  I didn't try the node_env option.

**Comment by Robert-W** [comment]
thanks @mcdemarco, we got rid of that property since we switched to passport to handle authentication. If you plan to roll your own authentication and want it to check the audience on tokens, you can add that back in. That was the original purpose for that.

**Comment by mcdemarco** [comment]
Just an FYI, I had trouble turning authentication back on.  Eventually I found a passport strategy in an old branch, but there doesn't seem to be one on master or develop.
