### ISSUE TITLE
Missing patient-specific scopes and validation in resource controller

### ISSUE THREAD

**Issue by G-2-Z** [Asymmetrik/node-fhir-server-core#65]
### Do you want to request a feature, improve documentation, or ask a question?
I would like to request the implementation of patient-specific scopes in accordance with the SMART on FHIR authorization specification. `patient/:resourceType.(read|write|*)`
As well as the associated validation in the resource controller. 

If i am not mistaken, this is currently only implemented for patients who are only allowed to view their own patient resource ([patient.controller.js#L44](https://github.com/Asymmetrik/node-fhir-server-core/blob/1e933bee1605310d0557dc480fc389977c0a5c18/src/server/profiles/patient/patient.controller.js#L44), [common.scopes.js#L14 (if profile == patient)](https://github.com/Asymmetrik/node-fhir-server-core/blob/1e933bee1605310d0557dc480fc389977c0a5c18/src/server/profiles/common.scopes.js#L14)), but not for the rest of the resources. Or am i missing something here?

**Comment by Robert-W** [comment]
Hi @G-2-Z,

Thanks for noticing this issue.  We do have some default scope checking on all resources. the `common.scopes.js` file is where we list out the possible scopes that could allow access to a resource and this is checked using express middleware. So for example, if someone requests an observation resource and has authenticated with the app. They would have scopes associated with them. The scopes set for observation would require one of the following scopes to be associated with the user for them to read an observation resource.

```
user/*.*
user/observation.*
user/observation.read
user/*.read',
observation/*.*
observation/Observation.*
observation/Observation.read
observation/*.read
```

The second part to that authentication is in the works now.   We are passing the scope contexts to the services (patient = 1, encounter = 1 etc...).  The plan is to add these to the queries as well as checking if they have the right permissions.  

For example:  If the user has the following scopes (scopes: patient/oberservation.read, patient: 1)

The service should generate the following example query:
select * from observation where observation.subject = 1.

We are planning to have this complete in the upcoming weeks.

**Comment by G-2-Z** [comment]
Thank you Robert. Good to hear. I'm looking forward to it.
