### ISSUE TITLE
"resourceType" always undefined when trying to POST a patient

### ISSUE THREAD

**Issue by sujaltv** [Asymmetrik/node-fhir-server-core#67]
I am trying to POST a patient's object:
```
{
        "resourceType": "Patient",
        "id": "2a269655-ca89-49f6-893d-baf301382c11",
        ...
}
```

But I always get the error, "resourceType expected 'Patient' but got undefined". I ran this in test mode (bypassing authentication). Is there a sample format or example of POST body?

Thanks.

**Comment by sujaltv** [comment]
I tried this on Postman, and this issue was a result of not properly stringifying the resource object (in Postman, you might have to escape `\` the quotes ).

**Comment by mcdemarco** [comment]
I am also having this problem but escaping the quotes did not help, nor did trying the request with curl.  In all cases the request body disappears, leading to the error about an undefined resource type.  The behavior is a lot like that described in [Postman bug #391](https://github.com/postmanlabs/postman-app-support/issues/391) where the request has become a GET after a redirect; I can pass in the resource type successfully using x-www-form-urlencoded, though that's not particularly helpful for the rest of the create process.
