### ISSUE TITLE
doseSimpleQuantity should be doseQuantity in stu3?

### ISSUE THREAD

**Issue by mcdemarco** [Asymmetrik/node-fhir-server-core#70]
I was following the FHIR 3.0.1 documentation [here](https://www.hl7.org/fhir/dosage.html) to implement  dosage in medicationStatement and noticed that my doseRanges were working but my doseQuantities were disappearing.  This seems to be because the server uses doseSimpleQuantity instead of doseQuantity, e.g., here:

https://github.com/Asymmetrik/node-fhir-server-core/blob/e05e59a736f6572439c0515f12f60bc44cf99758/src/server/standards/stu3/base/Dosage.js#L124

I don't know whether the name changed at some point, but doseSimpleQuantity seems to be incorrect now.

**Comment by jonterrylee** [comment]
#71 

Thanks @mcdemarco.  You are correct that it should be doseQuantity.  When we generate the Resources from the JSON schemas, it's incorrectly defined as doseSimpleQuantity.

"
            "doseSimpleQuantity": {
              "description": "Amount of medication per dose.",
              "$ref": "Quantity.schema.json#/definitions/Quantity"
            },
"

We're now generating the resources from Structure Definitions and will have those available shortly with DSTU2 and R4.  

We'll also have 2 new repos for graphql as well as a better FHIR starter.  I think both of these will be much improved from core and you should easily be able to move things over by just copying the services.

**Comment by jonterrylee** [comment]
Merged.  Let me know if you see any other issues.

Thanks
