### ISSUE TITLE
Getting Started URL is no longer valid

### ISSUE THREAD

**Issue by dominathan** [Asymmetrik/node-fhir-server-core#79]
Love this project.  Thanks for your work.

`http://localhost:3000/stu3/metadata` no longer works.  I had to use 
`http://localhost:3000/3_0_1/metadata`. Not sure the best way to fork your wiki.

**Comment by jonterrylee** [comment]
Thanks @dominathan for bringing that to our attention.  We've refactored a couple of things and version support was one of them.  I'm sure we'll have to redo the wikis as well.  We're hoping to have that updated today.

Thanks again

**Comment by jonterrylee** [comment]
WIKI has been updated.
