### ISSUE TITLE
Resource search parameters not implemented?

### ISSUE THREAD

**Issue by mcdemarco** [Asymmetrik/node-fhir-server-core#87]
### Do you want to request a feature, improve documentation, or ask a question?

No...

### Are you reporting a bug?

Yes.

**What is the current behavior?**

Resource searches fail with an invalid parameter error because the "resource" type is not found in sanitize.utils.js.

**What is the expected behavior?**

I think resource searches should restrict to the resource; for example, restrict a Condition search to a particular patient, as works here (but is not working for me on my server):
https://r3.smarthealthit.org/Condition?patient=7b1b9efd-50a4-4b8b-a772-a24aafe01f7f

**What are the steps to reproduce?**

Pass in a search query of resource type from the argument list for a particular service.  You don't need a sensible value to see the error.

**What OS are you using and what version of node.js and @asymmetrik/fhir-server-core are you running?**

MacOS 10.12.6, Node 10.5.0, and a branch of fhir-server-core off of develop commit 1e933bee1605310d0557dc480fc389977c0a5c18, but master and develop don't seem to have changed any w.r.t. sanitize.utils.js.

**Comment by jonterrylee** [comment]
@mcdemarco 

We're investigating now.

**Comment by mcdemarco** [comment]
Another search sanitizing issue I've noticed is that dates are checked against moment by the code, but the date type actually includes some boundary prefixes (eq, gt, etc).  So any date search query including them is rejected:  

https://www.hl7.org/fhir/search.html#date

E.g., https://r3.smarthealthit.org/Patient/?birthdate=1926-02-09 vs https://r3.smarthealthit.org/Patient/?birthdate=eq1926-02-09

**Comment by jonterrylee** [comment]
@mcdemarco yea we have a branch to fix the date issue.  There are 2 parts to this that should be fixed shortly.

**Comment by jonterrylee** [comment]
@mcdemarco 

The original plan for the date was to break it up into tokens to make it easier for the implementor to use.  This way we can validate the date portion of the string.

birthdate = eq1926-02-09 would transform into:
brithdate = { "comparator":  "eq", "date": "1926-02-09"  }

We may still decide to do this in the future but for the meantime, I have changed the sanitize to only validate that it is a string.  

Can you give this branch a try and see if it fixes your issue?  I've also added reference as a param type.  I'll check if there are other param types we're missing.
[branch](https://github.com/Asymmetrik/node-fhir-server-core/tree/fix/sanitize-params

**Comment by mcdemarco** [comment]
I'm still working on the branch without authentication (someone else is assigned to get authentication going), so I don't have an easy way to test a branch that requires it.  I may be able to try merging the changes in tomorrow.

**Comment by mcdemarco** [comment]
I was able to get the resource search working in my branch, but had trouble with Bundle.js __resource.toJSON on the sanitize-params branch that may or may not be due to my code.  In neither case could I get the date search working; it was still hitting moment in parseValue and coming up invalid if it had a prefix.

**Comment by jonterrylee** [comment]
@mcdemarco 

The fix has been merged in to the master branch.  Please let me know if you're still having any issues.

**Comment by mcdemarco** [comment]
It seems fine now; I found the solution to my toJSON problems in another issue (#80).
